# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "*-fabric" ]
  pull_request:
    branches: [ "*-fabric" ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/openjdk/jdk:17-ubuntu
    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Check Setting
        run: ./gradlew javaToolchains checkCompileOption
      - name: Build with Gradle
        run: ./gradlew build
      - name: Check Artifacts
        run: ls -al build/libs/
      - name: Upload failed test report
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          path: build/reports/tests/*
          name: Test-Report-${{ github.run_number }}
